services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      GF_SECURITY_ADMIN_USER: hu_devops
      GF_SECURITY_ADMIN_PASSWORD: hu@347654

    volumes:
      - /data/grafana/data:/var/lib/grafana
